### ISSUE TITLE
Remove the message board data model

### ISSUE THREAD

**Issue by ifireball** [redhat-beyond/Side-Hustle#12]
It seems like you've blindly copied code from the Beyond-totorial without thinking about what you are doing or asking questions about it. I do not expect your project to have the `Message` model since its not a message board! Nor doeit it need to have any model or any link to the admin UI at this point! Please remove the model classes and migrations that you've copied blindly and prepare a proper data model for your application to the 2nd demo.

**Comment by AshkenYariv** [comment]
Hi Barak, got it, we are on it.

**Comment by AshkenYariv** [comment]
@ifireball was deleted in this PR: https://github.com/redhat-beyond/Side-Hustle/pull/21
